[program:poi]
command=/srv/poi/fnm-exec ./node_modules/.bin/tsx src/app.ts
directory=/srv/poi
environment=
  NODE_ENV=production,
  BABEL_DISABLE_CACHE=1,
  POI_SERVER_DISABLE_LOGGER=1,
  POI_SERVER_DB=mongodb://localhost:27017/poi-production,
  POI_SERVER_PORT=17027,
  FNM_DIR=/srv/poi/.fnm,
  FNM_BIN=/srv/poi/.fnm-bin/fnm
user=www-data

[program:poi-hook]
command=/srv/poi/fnm-exec node hooks.js
directory=/srv/poi
environment=
  NODE_ENV=production,
  BABEL_DISABLE_CACHE=1,
  FNM_DIR=/srv/poi/.fnm,
  FNM_BIN=/srv/poi/.fnm-bin/fnm
user=poi
