export default {
  language: 'English',
  name: 'POI',
  description: 'Scalable KanColle browser and tool.',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: 'Weibo',
  'download-for': 'Download for',
  'linux-x64': 'Linux (x64)',
  'linux-deb-x64': 'Debian / Ubuntu (x64)',
  'linux-rpm-x64': 'Fedora / CentOS (x64)',
  'macos-x64': 'macOS (x64)',
  'win-ia32': 'Windows (x86) Portable',
  'win-ia32-setup': 'Windows (x86)',
  'win-x64': 'Windows (x64) Portable',
  'win-x64-setup': 'Windows (x64)',
  'stable-hint': 'Stable, for most users',
  'beta-hint': 'Beta, for new features',
  'other-versions': 'Other versions...'
}
