export default {
  language: '日本語',
  name: 'POI',
  description: '拡張可能な艦隊これくしょんブラウザ',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: 'Weibo',
  'download-for': 'ダウンロード: ',
  'linux-x64': '64 ビット Linux ヴァージョン',
  'linux-deb-x64': '64 ビット Debian / Ubuntu ヴァージョン',
  'linux-rpm-x64': '64 ビット Fedora / CentOS ヴァージョン',
  'macos-x64': '64 ビット macOS ヴァージョン',
  'win-ia32': '32 ビット Windows ヴァージョン',
  'win-ia32-setup': '32 ビット Windows インストーラ',
  'win-x64': '64 ビット Windows ヴァージョン',
  'win-x64-setup': '64 ビット Windows インストーラ',
  'stable-hint': '安定版・一般利用の方におすすめ',
  'beta-hint': '開発版・新機能が欲しいの方におすすめ',
  'other-versions': '他のヴァージョン',
}
