export default {
  language: '日本語',
  name: 'POI',
  description: '拡張可能な艦隊これくしょんブラウザ',
  github: 'GitHub',
  telegram: 'Telegram',
  opencollective: 'Help us via OpenCollective',
  weibo: 'Weibo',
  'download-for': 'ダウンロード: ',
  'linux-x64': '64 ビット Linux バージョン',
  'linux-deb-x64': '64 ビット Debian / Ubuntu バージョン',
  'linux-rpm-x64': '64 ビット Fedora / CentOS バージョン',
  'macos-x64': '64 ビット macOS バージョン',
  'win-ia32': '32 ビット Windows バージョン',
  'win-ia32-setup': '32 ビット Windows インストーラ',
  'win-x64': '64 ビット Windows バージョン',
  'win-x64-setup': '64 ビット Windows インストーラ',
  'stable-hint': '安定版・一般利用の方におすすめ',
  'beta-hint': '開発版・新機能が欲しいの方におすすめ',
  'other-versions': '他のバージョン',
  'telegram-group-link': 'https://t.me/joinchat/ENYTxwoB7sKsPQmgKEFzJw',
}
