export default {
  language: '正體中文',
  name: 'POI',
  description: '一個可擴展的艦隊 Collection 瀏覽器',
  github: 'GitHub',
  telegram: 'Telegram',
  weibo: '新浪微博',
  'download-for': '下載',
  'linux-x64': '64 位 Linux 版',
  'linux-deb-x64': '64 位 Debian / Ubuntu 版',
  'linux-rpm-x64': '64 位 Fedora / CentOS 版',
  'macos-x64': '64 位 macOS 版',
  'win-ia32': '32 位 Windows 版',
  'win-ia32-setup': '32 位 Windows 安裝包',
  'win-x64': '64 位 Windows 版',
  'win-x64-setup': '64 位 Windows 安裝包',
  'stable-hint': '正式版，適合大部分人使用',
  'beta-hint': '測試版，包含最新的功能',
  'other-versions': '下載其他版本'
}
