import { type DatabaseStatus, legacyMongoEpoch } from '../../contracts/database'
import {
  AACIRecord,
  BattleAPI,
  CreateItemRecord,
  CreateShipRecord,
  DropShipRecord,
  EnemyInfo,
  ItemImprovementRecipeAvailabilityFact,
  ItemImprovementRecipeCostFact,
  ItemImprovementRecipeUpdateFact,
  NightBattleCI,
  NightContactRecord,
  PassEventRecord,
  Quest,
  QuestReward,
  RecipeRecord,
  RemodelItemRecord,
  SelectRankRecord,
  ShipStat,
} from '../../models'

export const getMongoDatabaseStatus = async (): Promise<DatabaseStatus> => {
  const [
    createShipObservations,
    createItemObservations,
    remodelItemObservations,
    dropShipObservations,
    passEventObservations,
    battleApiObservations,
    nightContactObservations,
    aaciObservations,
    nightBattleCiObservations,
    selectRankStates,
    recipeAggregates,
    shipStatAggregates,
    enemyInfoAggregates,
    questDefinitions,
    questRewardDefinitions,
    itemImprovementAvailabilityFacts,
    itemImprovementCostFacts,
    itemImprovementUpdateFacts,
  ] = await Promise.all([
    CreateShipRecord.estimatedDocumentCount().exec(),
    CreateItemRecord.estimatedDocumentCount().exec(),
    RemodelItemRecord.estimatedDocumentCount().exec(),
    DropShipRecord.estimatedDocumentCount().exec(),
    PassEventRecord.estimatedDocumentCount().exec(),
    BattleAPI.estimatedDocumentCount().exec(),
    NightContactRecord.estimatedDocumentCount().exec(),
    AACIRecord.estimatedDocumentCount().exec(),
    NightBattleCI.estimatedDocumentCount().exec(),
    SelectRankRecord.estimatedDocumentCount().exec(),
    RecipeRecord.estimatedDocumentCount().exec(),
    ShipStat.estimatedDocumentCount().exec(),
    EnemyInfo.estimatedDocumentCount().exec(),
    Quest.estimatedDocumentCount().exec(),
    QuestReward.estimatedDocumentCount().exec(),
    ItemImprovementRecipeAvailabilityFact.estimatedDocumentCount().exec(),
    ItemImprovementRecipeCostFact.estimatedDocumentCount().exec(),
    ItemImprovementRecipeUpdateFact.estimatedDocumentCount().exec(),
  ])

  return {
    backend: 'mongodb',
    status: 'up',
    epoch: legacyMongoEpoch,
    estimatedCounts: {
      createShipObservations,
      createItemObservations,
      remodelItemObservations,
      dropShipObservations,
      passEventObservations,
      battleApiObservations,
      nightContactObservations,
      aaciObservations,
      nightBattleCiObservations,
      selectRankStates,
      recipeAggregates,
      shipStatAggregates,
      enemyInfoAggregates,
      questDefinitions,
      questRewardDefinitions,
      itemImprovementAvailabilityFacts,
      itemImprovementCostFacts,
      itemImprovementUpdateFacts,
    },
  }
}
